### ISSUE TITLE
Potential Assumption made about DOM and JavaScript

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-0-the-dom-introduction#4]
### Canvas Link

https://learning.flatironschool.com/courses/6956/pages/introduction-to-the-dom?module_item_id=562269

### Concern

When we use JavaScript and DOM programming to modify the DOM and change what the user sees, the underlying code is not modified: if we refresh the page, it goes back to its original state.

STATEMENT ABOVE IS NOT TRUE WHEN WE CALL: document.write("something");

HOWEVER, it would be true if you do not use document.write("something");

### Suggested Changes

When we use JavaScript and DOM programming to modify the DOM and change what the user sees, the underlying code is not modified: if we refresh the page, it goes back to its original state. EXCEPT: document.write("something"); this will change the page.

**Comment by lizbur10** [comment]
Hi @ckelly38 ! Actually, the statement is true of document.write() as well. If you use document.write("something"), it will change the page in the DOM, but it does not change the underlying HTML. When you refresh the page, it will be restored to its original state.

I hope this helps! 💙
